### PR TITLE
Vendor `wheel` package for offline fixture

### LINKED ISSUE #240: Offline integration tests are failing
This is happening on `main` as well as in PRs (e.g. #238 #239):

```
            [builder] Paketo Buildpack for Pip Install 1.2.3
            [builder]   Executing build process
            [builder]     Running 'pip install --requirement requirements.txt --ignore-installed --exists-action=w --no-index --find-links=/workspace/vendor --compile --user --disable-pip-version-check'
            [builder]       Looking in links: /workspace/vendor
            [builder]       Processing ./vendor/Flask-2.1.3-py3-none-any.whl (from -r requirements.txt (line 1))
            [builder]       Processing ./vendor/Jinja2-3.1.2-py3-none-any.whl (from -r requirements.txt (line 2))
            [builder]       Processing ./vendor/MarkupSafe-2.1.1.tar.gz (from -r requirements.txt (line 3))
            [builder]         Installing build dependencies: started
            [builder]         Installing build dependencies: finished with status 'error'
            [builder]         error: subprocess-exited-with-error
            [builder]
            [builder]         × pip subprocess to install build dependencies did not run successfully.
            [builder]         │ exit code: 1
            [builder]         ╰─> [4 lines of output]
            [builder]             Looking in links: /workspace/vendor
            [builder]             Processing ./vendor/setuptools-63.2.0-py3-none-any.whl
            [builder]             ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
            [builder]             ERROR: No matching distribution found for wheel
            [builder]             [end of output]
            [builder]
            [builder]         note: This error originates from a subprocess, and is likely not a problem with pip.
            [builder]       error: subprocess-exited-with-error
            [builder]
            [builder]       × pip subprocess to install build dependencies did not run successfully.
            [builder]       │ exit code: 1
            [builder]       ╰─> See above for output.
            [builder]
            [builder]       note: This error originates from a subprocess, and is likely not a problem with pip.
            [builder] pip install failed:
            [builder] error: exit status 1
            [builder] ERROR: failed to build: exit status 1
            ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51
```

### PR DESCRIPTION
**Pull request by thitch97**
## Summary
Updates vendored packages for offline fixture. Resolves #240 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by thitch97** [comment]
Vendoring the missing package from the errors seen in #240 solved the issue but I haven't quite ascertained what changed to cause the failures. I noticed, however, that in #142 the same thing was done for `setuptools` which gives me a bit of confidence as far as precedent.

**Comment by robdimsdale** [comment]
> I haven't had time yet to look into it and the answer may be simple but I wonder why either of those two need to be vendored at all given we bundle them with pip.

That's my concern too. [`wheel` is bundled with the `pip` dependency](https://github.com/paketo-buildpacks/pip/blob/7a003b6a7e3427a17663f59cb2a623f4a71b1ff8/dependency/actions/compile/entrypoint#L67), so why do we need to vendor it again?

**Comment by thitch97** [comment]
@robdimsdale Perhaps we get this change in and create an issue to investigate the need to re-vendor `wheel` and `setuptools`? My preliminary investigation didn't point me to anything but I'd be willing to dig into it further.

**Comment by robdimsdale** [comment]
Sure. It's probably time for us to dig in a bit deeper to the topic of vendoring `wheel`, `setuptools`, etc, but I agree that we should unblock the pipelines.

**Review by robdimsdale — APPROVED** [review]

**Pull request merged**
